// src/pages/rich_content/index.tsx
import Taro, { PureComponent, Config } from '@tarojs/taro';
import { View } from '@tarojs/components';

import { queryRichContent } from './services';
import './index.less';

class RichContent extends PureComponent {
  config: Config = {
    usingComponents: {
      parser: '../../components/parser/parser'
    }
  };

  parser: any;

  componentDidMount() {
    const { url, title } = this.$router.params;
    Taro.showNavigationBarLoading();
    Taro.setNavigationBarTitle({ title });
    queryRichContent({
      url
    }).then(res => {
      if (!this.parser.html) this.parser.setContent(res);
      Taro.setStorage({
        key: title,
        data: res
      });
    });
    Taro.getStorage({ key: title })
      .then(res => {
        this.parser.setContent(res.data);
      })
      .catch(() => null);
  }

  render() {
    return (
      <View className="rich-content">
        <parser ref={e => (this.parser = e)} selectable onLoad={() => Taro.hideNavigationBarLoading()} />
      </View>
    );
  }
}

export default RichContent;

// src/pages/RichContent/index.vue
<template>
  <parser class="about__desc" :html="content" selectable showWithAnimation />
</template>
<script>
export default {
  data() {
    return {
      content: ""
    };
  },
  onLoad(options) {
    wx.showNavigationBarLoading();
    if (options.type === "affiche") {
      wx.setNavigationBarTitle({ title: "公告" });
      this.$api.getAffiche(options.id).then(res => {
        this.content = res.affiche.content;
        wx.hideNavigationBarLoading();
      });
    } else {
      this.$api
        .getArticle(options.id)
        .then(res => {
          const { content, title } = res;

          wx.setNavigationBarTitle({ title });
          return content;
        })
        .then(content => {
          this.$api.getOSSContent(content).then(res => {
            this.content = res;
            wx.hideNavigationBarLoading();
          });
        });
    }
  }
};
</script>

<style lang="scss" scoped>
parser {
  padding: 30rpx;
}
</style>
